

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  poll-service:
    build:
      context: ./poll-service
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    networks:
      - app-network

  vote-service:
    build:
      context: ./vote-service
      dockerfile: Dockerfile
    ports:
      - "5003:5002"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: voting1
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
